### PR TITLE
Gui system and prompt for querying prior

### LINKED ISSUE #8: Graphical User Interface
Graphical User Interface for allowing the user to interact with the Active Learning Component. The user input should then be parsed by the Parser, whereupon it should be forwarded to the Data Storage. The database may also be used for audio playback.

See #7 and #9

### LINKED ISSUE #16: Implement static emotion-rating system for prior
Implement a static emotion-rating system in the GUI which takes input in the form of -1 to 1. 

See #7

### PR DESCRIPTION
**Pull request by sporreking**
Closes #8 
Closes #16

### CODE REVIEW

**Review by caspiansusskind — CHANGES_REQUESTED** [review]
GUI must be on main thread on Mac OS.

**Comment by sporreking** [comment]
The main application will now be launched on its own thread with a `main()` function, while the GUI system is run on the main thread.

**Comment by sporreking** [comment]
fixed small bug where arguments from *window_initializer* were not being spread into *event_processor*, which meant that all arguments accumulated in the first parameter.

**Review by caspiansusskind — APPROVED** [review]
Looks good!

**Pull request merged**
