### PR TITLE
feat: feature extraction

### LINKED ISSUE #41: Implement feature extraction
As of now the features number in 6670  which is too much. Look into a smaller set of features, extracted via for example librosa library in python.

### PR DESCRIPTION
**Pull request by tediiieee**
note:
* uses songs_info.csv as format for metadata
* only tested on emo-music
* data located locally in a folder called data* data located locally in a folder called data in root in root

csv data should be in:
LiU-AI-Project-Active-Learning-for-Music\data\emo-music-features\annotations
image

songs should be in:
LiU-AI-Project-Active-Learning-for-Music\data\emo-music-features\clips_45sec\clips_45seconds
image

new issue created #46 
Closes #41

### CODE REVIEW

**Review by sporreking — CHANGES_REQUESTED** [review]
split song output into time-series

**Comment by MattiasBeming** [comment]
Runtime for feature extraction on the mp3 files from emo-music is around 
23 min (i7-8700k @4.7GHz)
32 min (i5-8600k @4.3GHz)

**Review by Ludvig-Joborn — APPROVED** [review]
Very well done.

**Review by sporreking — APPROVED** [review]

**Comment by sporreking** [comment]
Approving due to word from @Ludvig-Joborn

**Pull request merged**
